# Generated by Django 2.1 on 2018-08-23 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trouble_name', models.CharField(max_length=50, unique=True, verbose_name='故障类型')),
                ('trouble_influence', models.IntegerField(choices=[(0, '不需要重启，不影响主机运行'), (1, '需要重启，影响主机运行')], default=0, verbose_name='是否影响主机')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
