# Generated by Django 2.1 on 2018-08-23 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('troubleinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=50, verbose_name='主机IP')),
                ('application_lines', models.CharField(max_length=50, verbose_name='应用名称')),
                ('host_sn', models.CharField(max_length=20, verbose_name='SN编号')),
                ('problem_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('repair_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('problem_desc', models.CharField(max_length=50, verbose_name='更换备件')),
                ('problem_info', models.CharField(max_length=50, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='登记时间')),
                ('factory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Serverinfo', verbose_name='机型')),
                ('idc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.IDCinfo', verbose_name='所属机房')),
                ('server_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Servefactoryrinfo', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '服务器故障',
                'verbose_name_plural': '服务器故障',
            },
        ),
        migrations.AlterModelOptions(
            name='trouble_type',
            options={'verbose_name': '故障类型', 'verbose_name_plural': '故障类型'},
        ),
        migrations.AddField(
            model_name='server_problem',
            name='trouble_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='troubleinfo.Trouble_type', verbose_name='故障类型'),
        ),
    ]
