# Generated by Django 2.1 on 2018-08-23 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0002_auto_20180823_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_problem',
            name='problem_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='故障报修时间'),
        ),
        migrations.AlterField(
            model_name='server_problem',
            name='repair_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='故障维修时间'),
        ),
    ]
