# Generated by Django 2.1 on 2018-08-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0003_auto_20180823_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_problem',
            name='application_lines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Application_info', verbose_name='应用名称'),
        ),
    ]
