# Generated by Django 2.0 on 2018-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0004_auto_20180823_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble_type',
            name='trouble_influence',
            field=models.IntegerField(choices=[(0, '不需要重启，不影响主机运行'), (1, '需要重启，影响主机运行')], default=0, help_text='是否需要重启', verbose_name='是否影响主机'),
        ),
        migrations.AlterField(
            model_name='trouble_type',
            name='trouble_name',
            field=models.CharField(help_text='故障类型', max_length=50, unique=True, verbose_name='故障类型'),
        ),
    ]
