# Generated by Django 2.0 on 2018-09-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0005_auto_20180825_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble_type',
            name='trouble_desc',
            field=models.CharField(default='', help_text='故障描述', max_length=50, verbose_name='故障描述'),
        ),
    ]
