# Generated by Django 2.0 on 2018-09-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0006_trouble_type_trouble_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble_type',
            name='trouble_desc',
            field=models.CharField(default='物理机硬件故障', help_text='故障描述', max_length=50, verbose_name='故障描述'),
        ),
    ]
