# Generated by Django 2.0 on 2018-11-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troubleinfo', '0007_auto_20180922_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_problem',
            name='factory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factoryname', to='baseinfo.Servefactoryrinfo', verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='server_problem',
            name='server_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Serverinfo', verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='server_problem',
            name='trouble_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='troubleinfo.Trouble_type', verbose_name='故障类型'),
        ),
    ]
