# Generated by Django 2.1 on 2018-08-22 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=50, verbose_name='机房名称')),
                ('idc_address', models.CharField(max_length=50, verbose_name='机房地址')),
                ('idc_tag', models.CharField(max_length=50, unique=True, verbose_name='机房标识符')),
                ('idc_leader', models.CharField(max_length=50, verbose_name='机房负责人')),
                ('idc_leader_phone', models.CharField(max_length=50, verbose_name='机房负责人联系方式')),
                ('idc_desc', models.CharField(max_length=50, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
        migrations.CreateModel(
            name='Servefactoryrinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=50, unique=True, verbose_name='供应商名称')),
                ('factory_address', models.CharField(max_length=50, verbose_name='公司地址')),
                ('factory_category', models.IntegerField(choices=[(0, '原厂商'), (1, '集成商')], default=1, verbose_name='厂商类型')),
                ('factory_leader', models.CharField(max_length=50, verbose_name='项目负责人')),
                ('factory_leader_phone', models.CharField(max_length=50, verbose_name='项目负责人联系方式')),
                ('factory_desc', models.CharField(max_length=500, verbose_name='备注')),
                ('factory_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='Serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_category', models.CharField(max_length=50, unique=True, verbose_name='机型')),
                ('server_product', models.CharField(max_length=50, verbose_name='品牌')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('server_desc', models.CharField(max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '服务器机型',
                'verbose_name_plural': '服务器机型',
            },
        ),
    ]
