# Generated by Django 2.0 on 2018-08-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_application_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servefactoryrinfo',
            options={'ordering': ('factory_time',), 'verbose_name': '供应商信息', 'verbose_name_plural': '供应商信息'},
        ),
    ]
