# Generated by Django 2.0 on 2018-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_auto_20180824_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='server_config',
            field=models.CharField(default='', max_length=220, verbose_name='配置'),
        ),
    ]
