# Generated by Django 2.0 on 2018-11-02 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_serverinfo_server_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=50, verbose_name='产品线')),
                ('line_tag', models.CharField(max_length=50, unique=True, verbose_name='应用标识符')),
                ('line_owner', models.CharField(max_length=50, verbose_name='产品线负责人')),
                ('line_department', models.CharField(max_length=50, verbose_name='产品线事业部')),
                ('line_desc', models.CharField(max_length=500, verbose_name='产品线描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '应用类型',
                'verbose_name_plural': '应用类型',
            },
        ),
    ]
