# Generated by Django 2.0 on 2018-11-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0005_product_lines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_lines',
            options={'verbose_name': '产品线', 'verbose_name_plural': '产品线'},
        ),
        migrations.AddField(
            model_name='application_info',
            name='line_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Product_lines', verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='product_lines',
            name='line_tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='产品线标识符'),
        ),
    ]
