# Generated by Django 2.1 on 2018-08-22 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=40, verbose_name='主机IP')),
                ('host_sn', models.CharField(max_length=20, verbose_name='SN编号')),
                ('host_category', models.CharField(max_length=500, verbose_name='机型')),
                ('host_product', models.CharField(max_length=500, verbose_name='厂商名称')),
                ('host_cabinet', models.CharField(default='F05-B12', max_length=500, verbose_name='机柜')),
                ('host_number', models.IntegerField(default=0, verbose_name='U位')),
                ('host_info', models.CharField(max_length=500, verbose_name='配置')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('idc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.IDCinfo', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
    ]
