# Generated by Django 2.1 on 2018-08-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('pcinfo', '0002_auto_20180823_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcinfo',
            name='host_product',
        ),
        migrations.AddField(
            model_name='pcinfo',
            name='factory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Serverinfo', verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='pcinfo',
            name='server_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Servefactoryrinfo', verbose_name='机型'),
        ),
    ]
