# Generated by Django 2.1 on 2018-08-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcinfo', '0003_auto_20180823_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcinfo',
            name='server_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Servefactoryrinfo', verbose_name='厂商'),
        ),
    ]
