# Generated by Django 2.0 on 2018-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcinfo', '0004_auto_20180823_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcinfo',
            name='host_ip',
            field=models.CharField(max_length=40, unique=True, verbose_name='主机IP'),
        ),
        migrations.AlterField(
            model_name='pcinfo',
            name='host_sn',
            field=models.CharField(max_length=20, unique=True, verbose_name='SN编号'),
        ),
    ]
